
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/board_1?serverTimezone=Asia/Seoul&characterEncoding=UTF-8 #13.125.117.231    
    username: root
    password: ajh0203
#  mvc hiddenmethod filter enabled : true                       

  jpa:
    open-in-view: true
    hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
        use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
    generate-ddl: false
      

  jackson:
    serialization:
      fail-on-empty-beans: false

